{% set version = "3.4" %}

package:
  name: distcc
  version: {{ version }}

source:
  url: https://github.com/distcc/distcc/releases/download/v{{ version }}/distcc-{{ version }}.tar.gz
  sha256: 2b99edda9dad9dbf283933a02eace6de7423fe5650daa4a728c950e5cd37bd7d

build:
  number: 0
  skip: true  # [py<31]
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - autoconf
    - automake
    - python
  run:
    - python

test:
  imports:
    - include_server
  commands:
    - distcc --help
    - distccd --help
    - pump --help

about:
  home: https://distcc.github.io
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: a free distributed C/C++ compiler system

extra:
  recipe-maintainers:
    - nehaljwani
